# Generated by Django 2.0.2 on 2018-05-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='emotion',
        ),
        migrations.AddField(
            model_name='post',
            name='emotion',
            field=models.CharField(choices=[('b', 'Bad'), ('g', 'Good')], default='g', max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Emotion',
        ),
    ]
