# Generated by Django 2.0.2 on 2018-06-22 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180524_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('student_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports_given', to=settings.AUTH_USER_MODEL)),
                ('student_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
