# Generated by Django 2.0.2 on 2018-06-22 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
