# Generated by Django 2.0.2 on 2018-07-04 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_block'),
        ('api', '0006_support_created_at'),
    ]

    operations = [
    ]
